## debugging only
apiVersion: v1
kind: Service
metadata:
    name: mss-api-svc
spec:
    type: NodePort
    ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
      nodePort: 30001
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
      nodePort: 30002
    selector:
      app: mss-api