apiVersion: v1
kind: Service
metadata:
  name: mss-api-svc
spec:
  type: ClusterIP
  selector:
    app: mss-api
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443